name: .NET CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    
    - name: Restore dependencies
      run: |
        # Assuming the docker-compose issue is resolved, directly restore the solution
        dotnet restore Nexify.sln --ignore-failed-sources

    - name: Build
      run: dotnet build Nexify.sln --no-restore

    - name: Run Unit Tests
      run: dotnet test WebApiTesting/Tests/Tests.csproj

    - name: Run Integration Tests
      run: dotnet test WebApiTesting/IntegrationTests/IntegrationTestsTests.csproj
