name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore Shop.sln
      - name: Build
        run: dotnet build --no-restore src/Shop.Api/Shop.Api.csproj
      - name: Test
        run: dotnet test WebApiIntegrationTesting/Tests/Tests.csproj
